---
# Source: audius-creator-node/templates/backend-cm.yaml

apiVersion: v1
kind: ConfigMap
metadata:
  name: creator-node-backend-cm
  namespace: default
data:
  
  dbUrl: "postgres://postgres:postgres@creator-node-db-svc.default.svc.cluster.local:5432/audius_creator_node"
  
  redisHost: "creator-node-cache-svc.default.svc.cluster.local"
  redisPort: "6379"
  ipfsHost: "creator-node-ipfs-svc.default.svc.cluster.local"
  ipfsPort: "5001"
  creatorNodeEndpoint: "<SEE_README>"
  dataNetworkId: "99"
  dataProviderUrl: "https://poa-gateway.audius.co"
  dataRegistryAddress: "0xC611C82150b56E6e4Ec5973AcAbA8835Dd0d75A2"
  delegateOwnerWallet: "<SEE_README>"
  delegatePrivateKey: "<SEE_README>"
  discoveryProviderWhitelist: ""
  ethNetworkId: "3"
  ethOwnerWallet: "0xe886a1858d2d368ef8f02c65bdd470396a1ab188"
  ethProviderUrl: "https://mainnet.infura.io/v3/c569c6faf4f14d15a49d0044e7ddd668"
  ethRegistryAddress: "0x095284A8237b275aBB96E8587e60ed76983BE6A5"
  ethTokenAddress: "0xF0A4A438821d21e37150e9916569De7c156E898F"
  headersTimeout: "60000"
  identityService: "https://identityservice.audius.co"
  ipfsClusterIP: "<SEE_README>"
  ipfsClusterPort: "<SEE_README>"
  keepAliveTimeout: "5000"
  logLevel: "debug"
  maxAudioFileSizeBytes: "1000000000"
  setTimeout: "3600000"
  spOwnerWallet: "<SEE_README>"
  timeout: "3600000"
  userMetadataNodeUrl: "https://usermetadata.audius.co"


---
# Source: audius-creator-node/templates/db-cm.yaml

apiVersion: v1
kind: ConfigMap
metadata:
  name: creator-node-db-cm
  namespace: default
data:
  POSTGRES_DB: audius_creator_node
  POSTGRES_USER: postgres


