---
# Source: audius-identity-service/templates/backend-deploy.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: identity-backend
  namespace: default
spec:
  selector:
    matchLabels:
      release: identity
      tier: backend
  replicas: 1
  template:
    metadata:
      labels:
        release: identity
        tier: backend
      annotations:
        checksum/config: 14fd338ddbbe6f6293e3054d2680c3eec1a92f8d4c0b6d86cec30a732d817a3e
    spec:
      
      containers:
      - name: identity-backend
        imagePullPolicy: Always
        
        image: audius/identity-service:96517412a87868f4ac3e2ea5ce255fb7e828731b
        
        envFrom:
        - configMapRef:
            name: identity-backend-cm
        
        ports:
        - containerPort: 7000
        livenessProbe:
          httpGet:
            path: /health_check
            port: 7000
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 10
          failureThreshold: 30
        readinessProbe:
          httpGet:
            path: /health_check
            port: 7000
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 10
          failureThreshold: 30
        
        command: ["sh", "-c", "exec node src/index.js"]
        
        
      


---
# Source: audius-identity-service/templates/cache-deploy.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: identity-cache
  namespace: default
spec:
  selector:
    matchLabels:
      release: identity
      tier: cache
  replicas: 1
  template:
    metadata:
      labels:
        release: identity
        tier: cache
    spec:
      
      containers:
      - name: identity-cache
        image: redis:5.0.5
        ports:
        - containerPort: 6379


